[package]
name = "solana-frozen-abi-macro"
version = "0.1.0"
edition = "2018"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0.71", features = ["full"] }
log = "0.4"

[build-dependencies]
rustc_version = "0.4"